modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = true
versionRange = "[1.15.18,)"
ordering = "AFTER"
side = "BOTH"